import { readFileSync } from "node:fs";
import { PDFDocument } from "pdf-lib";
const bytes = readFileSync("C:/Users/andre/Downloads/SUNG JINWOO LVL 9.pdf");
const pdf = await PDFDocument.load(bytes, { ignoreEncryption: true });
console.log("pagine:", pdf.getPageCount());
const form = pdf.getForm();
const campi = form.getFields();
console.log("campi del modulo:", campi.length);
const perTipo = new Map();
for (const c of campi) perTipo.set(c.constructor.name, (perTipo.get(c.constructor.name) ?? 0) + 1);
console.log("tipi:", [...perTipo].map(([k, v]) => `${k}=${v}`).join(", "));
console.log("\nprimi 40 nomi campo:");
for (const c of campi.slice(0, 40)) console.log("  -", JSON.stringify(c.getName()));
